# Generated by Django 5.2.10 on 2026-01-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gestor'), ('operator', 'Operador'), ('viewer', 'Visualizador')], default='operator', max_length=20, verbose_name='Rol'),
        ),
    ]
