# Generated by Django 5.2.10 on 2026-01-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Marcar si es una empresa de demostración', verbose_name='Empresa Demo'),
        ),
    ]
