# Generated by Django 5.2.10 on 2026-02-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_is_demo_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('view', 'Ver'), ('login', 'Iniciar sesión'), ('logout', 'Cerrar sesión'), ('security_alert', 'Alerta de seguridad')], max_length=20, verbose_name='Acción'),
        ),
    ]
