# Generated by Django 5.2.10 on 2026-01-08 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Moneda')),
                ('tax_rate_default', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa de impuesto por defecto (%)')),
                ('timezone', models.CharField(default='America/Argentina/Buenos_Aires', max_length=50, verbose_name='Zona horaria')),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20, verbose_name='Formato de fecha')),
                ('fiscal_year_start', models.CharField(default='01-01', help_text='Formato: MM-DD', max_length=10, verbose_name='Inicio del año fiscal')),
                ('custom_fields', models.JSONField(blank=True, default=dict, verbose_name='Campos personalizados')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuraciones de Empresa',
            },
        ),
    ]
