# Generated by Django 5.2.10 on 2026-01-08 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('type', models.CharField(choices=[('sale', 'Venta'), ('purchase', 'Compra')], max_length=20, verbose_name='Tipo')),
                ('number', models.CharField(max_length=50, verbose_name='Número')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Impuesto')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='customers.customer', verbose_name='Cliente')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='suppliers.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='OperationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.operation', verbose_name='Operación')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_items', to='products.product', verbose_name='Producto/Servicio')),
            ],
            options={
                'verbose_name': 'Item de Operación',
                'verbose_name_plural': 'Items de Operación',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['company', 'type', '-date'], name='operations__company_a3197b_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['company', 'status'], name='operations__company_1db88f_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['company', 'type', 'number'], name='operations__company_bcc19b_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['customer'], name='operations__custome_bb8971_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['supplier'], name='operations__supplie_5c3336_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operation',
            unique_together={('company', 'type', 'number')},
        ),
    ]
