# Generated by Django 5.2.10 on 2026-01-08 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_membership_role'),
        ('customers', '0002_customer_customers_c_company_10527e_idx'),
        ('operations', '0002_alter_operation_created_by'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['company', 'date'], name='operations__company_4ddc60_idx'),
        ),
    ]
