# Generated by Django 5.2.10 on 2026-01-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_operation_operations__company_4ddc60_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total'),
        ),
    ]
