# Generated by Django 5.2.10 on 2026-01-08 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('product', 'Producto'), ('service', 'Servicio')], default='product', max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio')),
                ('unit_of_measure', models.CharField(default='unidad', max_length=20, verbose_name='Unidad de medida')),
                ('stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Stock')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Producto/Servicio',
                'verbose_name_plural': 'Productos/Servicios',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'active'], name='products_pr_company_73e7e4_idx'), models.Index(fields=['company', 'code'], name='products_pr_company_f8ef94_idx'), models.Index(fields=['company', 'type'], name='products_pr_company_4d012e_idx'), models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx')],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
